a, b = int(input('Введите переменную а: ')), int(input('Введите переменную b: '))
print('')
print('Сумма a+b:', a + b, end='\n')
print('Разность a-b:', a - b, end='\n')
print('Произведение a*b:', a * b, end='\n')
print('а в степени b:', a ** b, end='\n')
print('Остаток деления a на b:', a % b, end='\n')
print('Целая часть от деления a на b:', a // b, end='\n')
